server:
  port : 8088
spring :
  servlet :
    multipart :
      max-file-size : 10MB
      max-request-size : 10MB

  datasource :
    url : jdbc:mysql://localhost:3306/ShopApp
    driver-class-name : com.mysql.cj.jdbc.Driver
    username : root
    password : finn250302

  jpa :
    show-sql : true
    hibernate :
      ddl-auto : none
    properties :
      hibernate :
        dialect : org.hibernate.dialect.MySQL8Dialect
        format_sql : true
api :
  prefix : api/v1

jwt :
  expiration : 2592000
    #30 days = 30 * 24 * 60 * 60
  #secretKey : i2F65aO+I4AXRozfqtUnP+CAcSvOuU23Jl+aEsSS1KE=
  secretKey: IamDreamer

